name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: ✅ Tests
    steps:
      - uses: actions/checkout@v2

      - name: ⬇️ Install dependencies
        run: sudo apt install -y jq

      - name: ✅ Test
        run: (cd 02-jq/1-map_json; bash test.sh) &&
             (cd 02-jq/2-combine_filter_json; bash test.sh) &&
             (cd 02-jq/3-aggregate_sort_json; bash test.sh)
